
package com.curso.java.servicios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TratadoDeCadenas", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TratadoDeCadenas {


    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirCadenaMinuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadenaMinuscula")
    @ResponseWrapper(localName = "convertirCadenaMinusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadenaMinusculaResponse")
    public String convertirCadenaMinuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirPrimeraLetraCadenaMayuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirPrimeraLetraCadenaMayuscula")
    @ResponseWrapper(localName = "convertirPrimeraLetraCadenaMayusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirPrimeraLetraCadenaMayusculaResponse")
    public String convertirPrimeraLetraCadenaMayuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirCadenaMayuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadenaMayuscula")
    @ResponseWrapper(localName = "convertirCadenaMayusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadenaMayusculaResponse")
    public String convertirCadenaMayuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirPrimeraLetraCadenaMinuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirPrimeraLetraCadenaMinuscula")
    @ResponseWrapper(localName = "convertirPrimeraLetraCadenaMinusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirPrimeraLetraCadenaMinusculaResponse")
    public String convertirPrimeraLetraCadenaMinuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirCadaPalabraCadenaMayuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadaPalabraCadenaMayuscula")
    @ResponseWrapper(localName = "convertirCadaPalabraCadenaMayusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadaPalabraCadenaMayusculaResponse")
    public String convertirCadaPalabraCadenaMayuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

    /**
     * 
     * @param cadena
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "nuevaCadena", targetNamespace = "")
    @RequestWrapper(localName = "convertirCadaPalabraCadenaMinuscula", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadaPalabraCadenaMinuscula")
    @ResponseWrapper(localName = "convertirCadaPalabraCadenaMinusculaResponse", targetNamespace = "https://orobleto.github.io/octaviorobleto.github.io/", className = "https.orobleto_github_io.octaviorobleto_github.ConvertirCadaPalabraCadenaMinusculaResponse")
    public String convertirCadaPalabraCadenaMinuscula(
        @WebParam(name = "cadena", targetNamespace = "")
        String cadena);

}
